language: python
services:
- docker
python:
- '3.6'
install:
- make deps
script:
- make test
- make lint
- make docker_build
- make docker_push
dd:
  secure: rLDkBb7ZsK1KJ2rNyXHQY+5A8sdhQLC2QWAMZXhckzYLTtjlQ5lwppV7A1REnq4kOz/wfvUnUPR5p7lp9q2VgzJYIZNhtTOfpZDz9JdrOlp7FVmTUlc3L4ROaiUSWZQriJjtpUfW+fxzzro8QaOHKZ2anv7Z26Rm+pQ6fXI01E2XvkrWp4gDm0C51PrdXM9/3ZscqqUtJf/e+a1F3GxM0wsbr8K6X7zBqAvG/VS0Q2piC1KjymdPZyAzQ3b0gwia/QPVbB9WyrxS/IAHXJNwVTGaZM0NpTegEcHQpARJWqycuwtSg+2F/gWHRiy6ymEYjPBezxdRFIc/BOzRzTmAJU5pfc/mSjxn2ImJTUfla8mh5StSUDhqShK8pmNbvm0ohBpHkZWcqgXWF/8Z3Y5KjcLGXIO1qcmL65CKaAjNfAOeHjeb+YyLPJFsBbEqw0zRri5iaJ7Fq20E6OoVwiPOxstNfw5QwErJ1vwq758MGuaPsrWkkU7WEENAbxLS+xP1CSCD0GICbNoDVvtNGqJOB0CKwHKJwElB6+EjsEjqb3Byvfsdupe3kTQHrKWL7q8bfY2ZNHKXcKGyAfxz47ArxvBsOGWqcG0aqglbh+zK6k0yd8O2de2GJZAM7vHjn1hjaZa7xCNnrB2bhA/Q6sGxcIN0cCCcNX/GR8RI02/p2TI=
