language: python
services:
- docker
python:
- '3.6'
install:
- make deps
script:
- make test
- make test_xunit
- make lint
- make docker_build
- make docker_push
dd:
  secure: rLDkBb7ZsK1KJ2rNyXHQY+5A8sdhQLC2QWAMZXhckzYLTtjlQ5lwppV7A1REnq4kOz/wfvUnUPR5p7lp9q2VgzJYIZNhtTOfpZDz9JdrOlp7FVmTUlc3L4ROaiUSWZQriJjtpUfW+fxzzro8QaOHKZ2anv7Z26Rm+pQ6fXI01E2XvkrWp4gDm0C51PrdXM9/3ZscqqUtJf/e+a1F3GxM0wsbr8K6X7zBqAvG/VS0Q2piC1KjymdPZyAzQ3b0gwia/QPVbB9WyrxS/IAHXJNwVTGaZM0NpTegEcHQpARJWqycuwtSg+2F/gWHRiy6ymEYjPBezxdRFIc/BOzRzTmAJU5pfc/mSjxn2ImJTUfla8mh5StSUDhqShK8pmNbvm0ohBpHkZWcqgXWF/8Z3Y5KjcLGXIO1qcmL65CKaAjNfAOeHjeb+YyLPJFsBbEqw0zRri5iaJ7Fq20E6OoVwiPOxstNfw5QwErJ1vwq758MGuaPsrWkkU7WEENAbxLS+xP1CSCD0GICbNoDVvtNGqJOB0CKwHKJwElB6+EjsEjqb3Byvfsdupe3kTQHrKWL7q8bfY2ZNHKXcKGyAfxz47ArxvBsOGWqcG0aqglbh+zK6k0yd8O2de2GJZAM7vHjn1hjaZa7xCNnrB2bhA/Q6sGxcIN0cCCcNX/GR8RI02/p2TI=
deploy:
  provider: heroku
  app: dry-caverns-25266
  api_key:
    secure: nFQ7dCUSfIaTpFWYfpHRyAZdckazDD7ea0+RKxujAxwtb+4JQNGDG3TBdwJFtV3r/jXsVZUbZe0KtSzOsdy0QRtcUK0mMb4XoqKH+fyN8+5+4Any5lBokH5UvU7iUZMYvI7dlwVo3FKq2c1X1AeOQG4pdtCEG+BicGvnuHcfjG8SI3IEruWeVG2VAh5Y+BG8LdSB6LMBxkp/2mnsmIlAFzZGs4pxT3rkpnYy7wA188dF5nTYax46HLVvdH7lc4G3UmxdkOX/65VitJclRIfkkqVPYTM/fFi7ClW3qUp5zYpL3gOJ48mEnLL18ixnYnVF/TRzZHS3ZfwoEDebV8S8p7Jr/munORfOsVSEtGaLPN2/nju/AxpLIGGRUDR1vu/oYiTMD9rSSoNbi06dJh7ALeOtV7Sbe+ibV05Rtc5o+oy9OnSJsmiiO0XnQ+51UqeWBHeRpe3lXR3aJ8s0N1/Es6cyzlBrzdckAU+ArfLV3tj6zv6cUxJuvJPRSN7FUiXFDizuMZTje6Y1DwULbLHD3pFDg2Fk8bQ4R4XcYC38zZrA1+NNraOhXmkGLv+biwSie5u4KU/alR1X4yXgJg6HzmV2C6cjdqfBtfzo25JPaNwvr332flYxYDDdVJK7o9CiRzeHW4vHgX2swkPGSed5zqDcUxFsGurYMKgFo3SvYuk=
